name: Caller Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-child-workflow:
    uses: ./.github/workflows/child-workflow.yml
    with:
      input1: 'value1'
      input2: 'value2'
