name: Child Workflow

on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string
      input2:
        required: true
        type: string

jobs:
  process-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Input 1: ${{ inputs.input1 }}"
          echo "Input 2: ${{ inputs.input2 }}"
